### ISSUE TITLE
BUG: False values get stripped

### ISSUE THREAD

**Issue by gradinarufelix** [code-q-web-factory/CodeQ.Revisions#13]
This is an isolated regression to #10.

# Steps to reproduce

- Install a distribution with Neos.Demo
- Add the following snippet in a file `Configuration/NodeTypes.HomePage.yaml`

```yaml
'Neos.Demo:Document.Homepage':
  properties:
    test:
      type: boolean
      defaultValue: false
      ui:
        label: Test
        inspector:
          group: document
```

- Run `./flow node:repair --node-type Neos.Demo:Document.HomePage` to set the default value
- Perform some random changes, e.g., text, to have an initial revision
- Perform some more changes
- Try to roll back to the first revision

# Error

The explicitly defined property value of `false` would be stripped by the rollback. One would then need to re-run `./flow node:repair` to set the default value.

# Possible solution

We introduced the truncation of false/null values primarily to deal with missing resources. So maybe we can restrict the truncation to specific cases, like missing resources or references - instead of generously applying it to all possible null/false values, as some of them might make sense.
